### ISSUE TITLE
PyCharm displays invalid warning when passing a str/int for an Enum field

### ISSUE THREAD

**Issue by fj-dt** [koxudaxi/pydantic-pycharm-plugin#269]
**Describe the bug**
First of all, I am not sure if this can be fixed in your plugin or not.
I think a piece of code will explain the issue better:

```python
from enum import Enum

from pydantic import BaseModel


class MyEnum(Enum):
    TEST = "1"


class MyModel(BaseModel):
    test: MyEnum


def main():
    my_model = MyModel(
        test="1"
    )
    print(my_model)


if __name__ == '__main__':
    main()
```

The issue is:

![image](https://user-images.githubusercontent.com/63464773/114297512-5a4fcc00-9ab1-11eb-8ab4-0b8b097b46a6.png)

It tells me to use an enum, but Pydantic is able to find the enum with a string (same thing if I change it to an integer). When I execute my script, the output is:

```python
test=<MyEnum.TEST: '1'>
```

This is disturbing because if the input comes from an HTTP request, the value will be a string, not an enum (and I want Pydantic to parse and validate it, not me).

**Expected behavior**
The IDE should not tell me that this is incorrect.

**Environments (please complete the following information):**
 - IDE: Professional 2021.1
 - OS: macOS 11.2.3 (20D91)
 - Pydantic Version 1.3
 - Plugin version 0.2.1

Thanks for your help!

**Comment by koxudaxi** [comment]
Hi @fj-dt 

The problem is not a bug.
You can disable or change the warning.
Please check these documents.

https://koxudaxi.github.io/pydantic-pycharm-plugin/type-checker-for-pydantic/

I put an example for working your code.

## project structure
```
.
├── your_app
│   ├── __init__.py
│   └── main.py
└── pyproject.toml
```
## pyproject.toml
```toml
[tool.pydantic-pycharm-plugin.parsable-types]

# str field may parse int and float
str = ["int", "float"]

# datetime.datetime field may parse int
"datetime.datetime" = [ "int" ]

# your_module.your_type field may parse str
"your_app.main.MyEnum" = [ "str" ]

[tool.pydantic-pycharm-plugin]
# You can set higlith level (default is "warning")
# You can select it from "warning",  "weak_warning", "disable"
parsable-type-highlight = "warning"

## If you set acceptable-type-highlight then, you have to set it at same depth.
acceptable-type-highlight = "disable"

```


![2021-04-12 22 20 17](https://user-images.githubusercontent.com/630670/114401074-88322f00-9bdd-11eb-84a8-8e7a9f08dec0.png)
