### ISSUE TITLE
Declaring field types as sub-classes of base types gets highlighted in 

### ISSUE THREAD

**Issue by tuukkamustonen** [koxudaxi/pydantic-pycharm-plugin#312]
Hi, thanks for the great plugin!

**Describe the bug**

When using sub-classed `Constrained*` fields, `Expected type '...', got '...' instead.` error is shown.

See this example (using `StrictStr` which is inherited from `ConstrainedStr`):

![image](https://user-images.githubusercontent.com/94327/120186109-bd412200-c21b-11eb-89a4-2cdcdf4bc332.png)

It reproduces even when subclassing from base types, ie. `str`:

```py
import pydantic

class MyStr(str):
    pass

class MyModel(pydantic.BaseModel):
    field: MyStr

MyModel(field='')
```

**To Reproduce**

Above.

**Expected behavior**

There's shouldn't be error.

**Screenshots**

Uh, above.

**Environments (please complete the following information):**

 - IDE: PyCharm Professional 2021.1
 - OS: Kubuntu 20.04 LTS
 - Pydantic Version: 1.8.2
 - Plugin version: 0.3.3

**Comment by tuukkamustonen** [comment]
What is unfortunate here, is that declaring fields as sub-classes (above) is the only to avoid `mypy` nag about them. If you use `constr()` et al. mypy will report error.

**Comment by koxudaxi** [comment]
@tuukkamustonen 


The problem is not a bug.
You can disable or change the warning.
Please check these documents.

https://koxudaxi.github.io/pydantic-pycharm-plugin/type-checker-for-pydantic/

I put an example for working your code.

## project structure
```
.
├── your_app
│   ├── __init__.py
│   └── main.py
└── pyproject.toml
```
## pyproject.toml
```toml
[tool.pydantic-pycharm-plugin.parsable-types]

# str field may parse int and float
str = ["int", "float"]

# datetime.datetime field may parse int
"datetime.datetime" = [ "int" ]

# your_module.your_type field may parse str
"your_app.main.MyStr" = [ "str" ]

[tool.pydantic-pycharm-plugin]
# You can set higlith level (default is "warning")
# You can select it from "warning",  "weak_warning", "disable"
parsable-type-highlight = "warning"

## If you set acceptable-type-highlight then, you have to set it at same depth.
acceptable-type-highlight = "disable"

```

![Screenshot from 2021-06-01 01-15-22](https://user-images.githubusercontent.com/630670/120219898-e5aa3a00-c276-11eb-9b2f-b96e74d6ce4f.png)
